// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNTsU43KSNKwjGG6527clrqSIKz_9Tab4',
    appId: '1:773132638586:web:402fb2974ee12d3659dec3',
    messagingSenderId: '773132638586',
    projectId: 'g-tech-admin',
    authDomain: 'g-tech-admin.firebaseapp.com',
    storageBucket: 'g-tech-admin.firebasestorage.app',
    measurementId: 'G-FRK0QZBVYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ILb7GTvkXtwcGytfVLVvITOPmlF1WkM',
    appId: '1:773132638586:android:ccdbc9b6629f780959dec3',
    messagingSenderId: '773132638586',
    projectId: 'g-tech-admin',
    storageBucket: 'g-tech-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoGDHD9WreiDbbAYEnZwKMoKqDvT2pavs',
    appId: '1:773132638586:ios:a24a6df26dd1782259dec3',
    messagingSenderId: '773132638586',
    projectId: 'g-tech-admin',
    storageBucket: 'g-tech-admin.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoGDHD9WreiDbbAYEnZwKMoKqDvT2pavs',
    appId: '1:773132638586:ios:a24a6df26dd1782259dec3',
    messagingSenderId: '773132638586',
    projectId: 'g-tech-admin',
    storageBucket: 'g-tech-admin.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNTsU43KSNKwjGG6527clrqSIKz_9Tab4',
    appId: '1:773132638586:web:402fb2974ee12d3659dec3',
    messagingSenderId: '773132638586',
    projectId: 'g-tech-admin',
    authDomain: 'g-tech-admin.firebaseapp.com',
    storageBucket: 'g-tech-admin.firebasestorage.app',
    measurementId: 'G-FRK0QZBVYZ',
  );

}